---
dataset:
  name: 'random50'
  raw_graphs_file: 'data/graphs/random50_nodecount=15_edgeprob=0.2.g6'
  fname: 'data/graphs/graph=random50-node=15-path=shortest-step=multi.pkl'
  n_graph: 50
  n_isomorph: 20
  n_node: 15
  max_pathlen: 8
  batch_size: 128
  split_params:
    mode: 'random'
    train_prop: 0.75
model:
  lr: 0.0003
  architecture: 'a.f.a.f'
  n_heads: 2
  embed_dim: 64
  mlp_dim: 32
wandb:
  project: 'graph-subgoal-v4'
  save_dir: 'checkpoints/'
checkpoint:
  monitor: 'val/acc'
  mode: 'max'
  save_top_k: -1
  save_last: True
  every_n_epochs: 20
trainer:
  log_every_n_steps: 10
  val_check_interval: 20
  max_epochs: 100